### PR TITLE
Ts add vignettes

### PR DESCRIPTION
**Pull request by TomSmithCGAT**
@csdaw - Would you mind taking a look at the SILAC vignette. If you have longer comments you don't want to add here, happy to talk in person

### CODE REVIEW

**Comment by csdaw** [comment]
Going through code and text now. Just a first thing, am I okay to remove objects that are created but never used? e.g. https://github.com/CambridgeCentreForProteomics/camprotR/blob/cec8e67f8dda8ab890a142dd47d8916854be8c6e/vignettes/SILAC.Rmd#L224-L231

**Comment by TomSmithCGAT** [comment]
Why would you want to do that? Random objects help to force the reader to work through it all properly and identify where the inefficiencies are 😜

**Comment by csdaw** [comment]
By that logic we should put an error at the very end, and the reader has only understood if they can fix it!

**Comment by TomSmithCGAT** [comment]
Don't tempt me..

**Comment by TomSmithCGAT** [comment]
All looks good to me. @csdaw, you happy if I squash and merge?

**Comment by csdaw** [comment]
@TomSmithCGAT Go for it!

**Pull request merged**
